---
- name:
  apt:
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - python3
    - python3-pip
    - python-setuptools
    state: latest
    update_cache: yes
  tags: docker
- name: Get docker key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags: docker
- name: Add docker packages to repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename|lower }} stable
  tags: docker
- name: Install docker
  apt:
    name: docker-ce
    state: latest
    update_cache: true
- name: Start docker service
  service:
    name: docker
    state: started
- name: pip docker
  pip:
    executable: pip3
    name: docker
